name: Mysql

on: [push]

jobs:
  container-job:
    run-on: ubuntu-latest
    container: node:10.18-jessie
    services: 
      mysql: 
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD=Viva_o_2tinr
    steps:
      - name: Validar codigo
        uses: actions/checkout@v3
      - name: instalar dependencias
        run: npm ci
        
      
