name: Mysql

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    
    container: 
      image: node:10.18-jessie
    
    services: 
      mysql: 
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Viva_o_2tinr
        
    steps:
      - name: Validar codigo (Checkout code)
        uses: actions/checkout@v3

      - name: Instalar dependencias (Install dependencies)
        run: npm ci
